#!/bin/sh
#
# Scan sysfs for nodes and trigger module loading and other coldplug business...
#


case "$1" in
	start)
		# Make sure database is up to date
		depmod -a
		echo "Probing for modules"
		if [ -f /etc/modules ] ; then
			for mod in `grep -v '^[ \t]*[#]' /etc/modules`; do
				modprobe $mod
			done
		fi
		. /etc/init.d/loadmods.sh
	;;

	stop)
		:
	;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1;
	;;
esac

exit $?
