#!/bin/sh
#
# Scan sysfs for nodes and trigger module loading and other coldplug business...
#


case "$1" in
	start)
		find /sys -name uevent -exec sh -c 'echo -n add > {}' \;
	;;

	stop)
		:
	;;

	*)
		echo $"Usage: $0 {start|stop}"
		exit 1;
	;;
esac

exit $?
