#!/bin/sh
if [ -n "$BOOTCMD" ] ; then
    echo "Evaluating BOOTCMD: sh -c \"$BOOTCMD\""
	/bin/sh -c "$BOOTCMD"
	# Continue here and let then also specify a BOOTFILE
fi
if [ -n "$BOOTFILE" ] ; then
	echo "Executing BOOTFILE: $BOOTFILE"
	exec "$BOOTFILE"
fi
if [ -r /etc/bootfile ] ; then
	BOOTFILE=`cat /etc/bootfile`
	echo "Executing bootfile: $BOOTFILE"
	exec "$BOOTFILE"
fi
echo "Executing bootfile FAILED"
exit 1
